/**
 * VORA Light quotes — Fun
 * Original brand voice. Do not dilute with cliché motivational copy.
 */
export const FUN_LIGHTS = [
  'Your brain has enough tabs open. Go open a window instead.',
  'Take life seriously. Just not all at once.',
  'You\'re allowed to laugh before everything is figured out.',
  'The best ideas usually arrive when you stop chasing them.',
  'Be proud of yourself. You\'ve survived every awkward moment so far.',
  'Rest isn\'t a reward. It\'s part of the recipe.',
  'If today feels heavy, carry only what belongs to today.',
  'Your future self called. They said, "Relax a little."',
  'Don\'t forget to look up. The sky changes every day for free.',
  'Perfection is expensive. Joy is surprisingly affordable.',
  'Drink some water. Your cells are trying their best.',
  'A five-minute walk has solved more problems than five more minutes of worrying.',
  'Your smile deserves more screen time than your notifications.',
  'Sometimes the bravest thing you can do is close the laptop.',
  'You don\'t have to bloom today. Just don\'t stop growing.',
  'Life isn\'t grading your performance. It\'s inviting your participation.',
  'You\'re not behind. You\'re simply writing a different story.',
  'The world gets brighter every time you choose curiosity over fear.',
  'Leave a little room in your plans. That\'s where the magic usually sneaks in.',
  'Be as kind to yourself as you are to strangers.',
  'Your coffee believes in you. Try not to disappoint it.',
  'If your brain starts arguing with itself, invite your heart into the meeting.',
  'Some things can wait. Joy is rarely one of them.',
  'Your to-do list isn\'t your personality.',
  'Take a deep breath. Even the ocean pauses between waves.',
  'A little nonsense keeps life from becoming too sensible.',
  'If you\'re smiling for no reason, that\'s a pretty good reason.',
  'Life isn\'t asking you to hurry. It\'s asking you to notice.',
  'You don\'t need a perfect day to have a beautiful moment.',
  'The smallest adventure usually begins with, "Let\'s just see."',
  'Your comfort zone is nice. Just don\'t let it steal your passport.',
  'Don\'t underestimate the power of a tiny win and a good snack.',
  'You can always restart. Life doesn\'t charge a reset fee.',
  'Some days are for conquering mountains. Some days are for folding laundry. Both count.',
  'You\'re not a machine. Even your phone asks for a recharge.',
  'If today isn\'t sparkling, add a little kindness. It goes with everything.',
  'Your inner child still has excellent ideas. Maybe let them pick once in a while.',
  'The best conversations rarely begin with perfect words.',
  'Be curious enough to surprise yourself.',
  'Today\'s tiny smile might become tomorrow\'s favorite memory.',
  'Your brain deserves a coffee break. Even your coffee needs one sometimes.',
  'Life isn\'t a race. It\'s more like a playlist. Skip what doesn\'t fit.',
  'You don\'t have to carry everything. Backpacks have limits for a reason.',
  'If you\'re waiting for the perfect moment, it probably stopped to pet a dog.',
  'Some detours become the best part of the story.',
  'You can outgrow a bad mood. Start with one good thought.',
  'Your future self won\'t remember every email. They\'ll remember how you felt.',
  'Don\'t forget to celebrate tiny victories. They grow up to become big ones.',
  'Be the kind of person your younger self would high-five.',
  'Life gets lighter when you stop trying to carry tomorrow.',
  'The world has enough critics. Try becoming your own favorite teammate.',
  'Some answers arrive only after you\'ve gone for a walk.',
  'Not every pause means you\'re lost. Sometimes you\'re just loading the next adventure.',
  'You don\'t need to sparkle every day. Stars take turns too.',
  'If you\'re overthinking, your imagination is asking for a better job.',
  'A smile doesn\'t solve everything. It just makes solving things a little nicer.',
  'Your happiness isn\'t hiding. It\'s usually waiting behind one small decision.',
  'The best version of you still knows how to laugh at bad jokes.',
  'Give yourself the same encouragement you\'d happily give your best friend.',
  'Life becomes much more interesting when curiosity gets promoted over fear.',
  'Your happiness called. It said, "Stop scrolling. I\'m outside."',
  'You don\'t have to win every day. Some days are just for collecting good stories.',
  'The best memories rarely begin with, "I stayed home because it was safer."',
  'Your comfort zone is cozy. Visit often. Don\'t move in.',
  'A tiny adventure is still an adventure.',
  'If life feels blurry, clean your glasses before your dreams.',
  'Your brain loves overthinking. Your heart votes for trying.',
  'Treat yourself like someone you\'re actually rooting for.',
  'Some days deserve productivity. Some days deserve perspective.',
  'Laugh at your mistakes. They\'re already laughing with you.',
  'If you\'re waiting for a sign, this sentence volunteered.',
  'Your future self is quietly hoping you\'ll be a little kinder to today\'s you.',
  'A bad day doesn\'t deserve the rest of your week.',
  'Life is surprisingly generous to people who stay curious.',
  'You\'re not late. You\'re arriving with better stories.',
  'Sometimes the smartest decision is to take a snack break first.',
  'You don\'t need a brand-new life. Sometimes a new playlist is enough.',
  'Leave a little room for unexpected joy. It rarely makes appointments.',
  'Your laugh is a better investment than another hour of worrying.',
  'The world becomes a little brighter every time you choose wonder instead of "what if."',
  'You don\'t need permission to enjoy your own life.',
  'If Plan A disappeared, it\'s probably making room for a better alphabet.',
  'Your inner child just smiled. Keep doing whatever caused that.',
  'Some days become unforgettable simply because you noticed them.',
  'The dishes will still be there. Your sunset might not.',
  'Don\'t wait for life to become lighter. Dance with it anyway.',
  'A little laughter can carry surprisingly heavy days.',
  'You\'re allowed to take yourself less seriously. Your dreams won\'t mind.',
  'Collect moments that make you forget to check your phone.',
  'The best souvenirs are stories you\'ll never get tired of telling.',
  'Life isn\'t asking for a flawless performance. It\'s asking for your favorite version of you.',
  'If your smile has been on vacation, maybe today is a good day to invite it back.',
  'Joy has terrible timing. That\'s why it\'s always a wonderful surprise.',
  'Grow older if you must. Growing boring is optional.',
  'The world gets more colorful every time you choose wonder over routine.',
  'You don\'t have to make today legendary. Making it meaningful is already enough.',
  'Your happiest memories won\'t remember how busy you were.',
  'Keep one pocket empty. That\'s where unexpected joy likes to hide.',
  'The best part of life is that it still knows how to surprise you.',
  'Smile. The future looks better on someone who\'s enjoying the journey there.',
] as const

export type FunLight = (typeof FUN_LIGHTS)[number]
