/**
 * VORA Light quotes — Success
 * Original brand voice. Do not dilute with cliché motivational copy.
 */
export const SUCCESS_LIGHTS = [
  'Your future is quietly shaped by the promises you keep when no one is watching.',
  'The life you\'re dreaming of is built by the days that feel the most ordinary.',
  'One brave decision can become the beginning of a completely different life.',
  'Success doesn\'t arrive with applause. It arrives after countless quiet mornings.',
  'The strongest people aren\'t fearless. They simply refuse to let fear make the final decision.',
  'Every step forward counts, even when it feels too small to matter.',
  'Your future remembers every choice your present decides to make.',
  'Keep building a life that doesn\'t need to be explained.',
  'The distance between who you are and who you could become is crossed one decision at a time.',
  'One day, you\'ll realize the hardest season was quietly preparing your greatest strength.',
  'Progress is often invisible until you stop and look back.',
  'Your next breakthrough may be hiding behind one more attempt.',
  'The people who change their lives rarely wait until they feel ready.',
  'Every sunrise gives your dream another chance to become real.',
  'Quiet determination will always outlast loud ambition.',
  'You don\'t have to move fast. You only have to keep moving.',
  'Success belongs to those who keep showing up after the excitement fades.',
  'The future isn\'t built by perfect moments. It\'s built by consistent ones.',
  'Your greatest advantage is becoming the person who keeps going.',
  'The life you\'ve imagined is already moving toward you with every courageous choice you make.',
  'One quiet habit repeated every day will outgrow a hundred moments of inspiration.',
  'The person you hope to become is already waiting inside today\'s decisions.',
  'Some dreams take longer because they\'re preparing you, not testing you.',
  'Success often whispers before it ever learns how to roar.',
  'Keep choosing progress, even when perfection keeps calling your name.',
  'Every chapter worth remembering begins with uncertainty.',
  'The hardest roads often lead to the stories you\'ll tell with pride.',
  'Your future isn\'t asking you to be perfect. It\'s asking you to begin.',
  'One small act of courage can echo for the rest of your life.',
  'Don\'t measure your growth against someone else\'s timeline.',
  'The strongest momentum is built on the days you almost gave up.',
  'Every promise you keep to yourself becomes another brick in your future.',
  'Success isn\'t found. It\'s created, one ordinary day at a time.',
  'The life you admire is quietly built behind closed doors.',
  'Every setback leaves behind something stronger than disappointment if you\'re willing to look for it.',
  'Confidence grows where consistency lives.',
  'Some opportunities arrive disguised as difficult mornings.',
  'Your greatest investment will always be the person you\'re becoming.',
  'The finish line moves closer every time you choose not to stop.',
  'Keep walking. The view changes long before you notice it.',
  'Your future doesn\'t ask for perfection. It asks for your next step.',
  'The strongest people keep moving, even when nobody notices.',
  'Every impossible dream was once dismissed as unrealistic.',
  'One meaningful decision can outshine years of hesitation.',
  'Greatness is built in moments too small for anyone else to celebrate.',
  'Don\'t wait for confidence. Let action introduce you to it.',
  'The life you\'ve imagined begins the moment comfort stops making your decisions.',
  'Some victories take years to reveal themselves.',
  'Keep planting seeds, even when the garden is still invisible.',
  'Your quiet effort today will become someone else\'s inspiration tomorrow.',
  'The road feels long only because you\'re becoming someone stronger with every mile.',
  'What feels like slow progress today may become your greatest advantage tomorrow.',
  'Every ending creates space for a beginning you couldn\'t see before.',
  'Discipline quietly accomplishes what motivation promises.',
  'Your greatest comeback begins with one more attempt.',
  'The world changes for those who keep showing up after disappointment.',
  'The future belongs to people who choose courage more often than comfort.',
  'Don\'t fear starting over. Fear never discovering what was possible.',
  'The strongest foundations are built long before anyone sees the finished masterpiece.',
  'One day you\'ll realize the person you admired was slowly becoming you all along.',
  'The future rewards those who stay faithful to the work long after the excitement fades.',
  'Every quiet morning you choose discipline over excuses becomes part of your legacy.',
  'Your greatest strength is built in moments when quitting feels reasonable.',
  'One choice made with courage can outgrow years of fear.',
  'The life you\'re waiting for is waiting for your next move.',
  'Extraordinary lives are often built from remarkably ordinary days.',
  'The distance between dreaming and becoming is crossed through daily decisions.',
  'Success grows where consistency is stronger than emotion.',
  'Keep becoming the person your younger self believed you could be.',
  'One day, the sacrifices you questioned will become the stories you\'re proud to tell.',
  'The most powerful progress is the kind no one notices until everything has changed.',
  'Every step you repeat with intention becomes part of the person you\'re creating.',
  'Don\'t rush the process. Strong roots are never built in a hurry.',
  'Your future is shaped less by talent than by the promises you refuse to break.',
  'The hardest seasons often produce the strongest versions of ourselves.',
  'There is no wasted effort when every step teaches you how to move forward.',
  'The courage to continue will always outlast the fear of beginning.',
  'Success quietly follows those who stop chasing shortcuts.',
  'Keep walking with purpose. The destination is already moving closer than it seems.',
  'One day, you\'ll thank yourself for choosing progress over perfection.',
  'The life you\'ve imagined is built one quiet decision at a time.',
  'Every challenge is an invitation to become someone you\'ve never been before.',
  'The people who change the world usually begin by changing themselves.',
  'Don\'t wait for the perfect opportunity. Become the person who creates one.',
  'One disciplined day may seem ordinary, but a thousand of them become extraordinary.',
  'Every sunrise arrives with another chance to rewrite your story.',
  'Your future isn\'t hidden in tomorrow. It\'s created by what you choose today.',
  'Keep going. Mountains are moved one stone at a time.',
  'The most remarkable journeys begin with a step no one else believes in.',
  'Sometimes the smallest decision becomes the biggest turning point.',
  'Your greatest breakthrough is often waiting behind one more act of courage.',
  'Never underestimate the quiet power of showing up again.',
  'The dream that stays with you is usually the one worth fighting for.',
  'Every season of growth asks you to let go of the person you\'ve outgrown.',
  'Success is less about reaching the top and more about refusing to stay where you started.',
  'One day, your perseverance will become the proof that impossible was only temporary.',
  'The future belongs to those who keep choosing hope over hesitation.',
  'The strongest version of you is being shaped by the moments you almost walked away.',
  'Your story changes the moment your excuses stop writing it.',
  'One day, you\'ll look back and realize that every ordinary step was quietly leading you somewhere extraordinary.',
] as const

export type SuccessLight = (typeof SUCCESS_LIGHTS)[number]
