/**
 * VORA Light quotes — Love
 * Original brand voice. Do not dilute with cliché motivational copy.
 */
export const LOVE_LIGHTS = [
  'The right love will never ask you to become someone you\'re not.',
  'Some people feel like home long before they know your story.',
  'Love grows strongest where honesty feels safe.',
  'The heart remembers kindness long after it forgets perfection.',
  'The most beautiful relationships are built on countless ordinary moments.',
  'You deserve the kind of love that feels like peace, not confusion.',
  'Sometimes love arrives quietly so you\'ll recognize it by how calm you feel.',
  'A heart that stays gentle is never a heart that loses.',
  'Real love never competes. It chooses you every day.',
  'The people meant for you will never make you question your worth.',
  'Love isn\'t about finding perfection. It\'s about choosing each other through imperfection.',
  'The smallest acts of care often become the biggest memories.',
  'The right person won\'t complete your life. They\'ll make it even brighter.',
  'Some souls recognize each other before words ever do.',
  'Kindness is love in its quietest form.',
  'The strongest hearts are the ones that remain open after disappointment.',
  'Love becomes unforgettable when it makes you feel free to be yourself.',
  'The safest place in the world is a heart that truly understands yours.',
  'Some people enter your life to change your future without ever planning to.',
  'The greatest love stories begin with two people choosing each other, again and again.',
  'The best kind of love makes you feel more like yourself, never less.',
  'A heart that feels safe blooms in ways fear never allows.',
  'The right person won\'t ask you to shrink so they can shine.',
  'Love is found in the little things we choose every single day.',
  'The deepest connections are built through thousands of quiet moments.',
  'You\'ll know it\'s real when peace becomes louder than uncertainty.',
  'Love isn\'t about finding someone perfect. It\'s about feeling perfectly understood.',
  'Some people arrive exactly when your heart is ready to believe again.',
  'The strongest relationships are built on honesty spoken with kindness.',
  'Being loved should never feel like earning permission to exist.',
  'The right love doesn\'t change who you are. It helps you become more of yourself.',
  'Some hugs say everything words never could.',
  'A gentle heart is one of the bravest things a person can choose to keep.',
  'Real love never asks you to perform. It simply welcomes you home.',
  'The people who truly love you will celebrate your growth, not fear it.',
  'Sometimes the greatest gift you can give is your undivided presence.',
  'Love grows where gratitude is spoken often and assumed rarely.',
  'Every lasting relationship is built one thoughtful choice at a time.',
  'The right person will never make authenticity feel risky.',
  'Love becomes extraordinary when two people never stop choosing kindness.',
  'Some people don\'t change your life with grand gestures. They change it by staying.',
  'The right love never rushes your healing. It walks beside it.',
  'Being deeply understood is one of the quietest forms of love.',
  'Love feels different when you no longer have to question where you stand.',
  'The strongest relationships are built on conversations that were hard to have.',
  'You shouldn\'t have to earn the love that was always meant for you.',
  'A peaceful heart is often the greatest love story of all.',
  'The most beautiful promises are the ones quietly kept.',
  'Real love notices the little things because it never stops paying attention.',
  'The people who truly love you will never ask you to hide your light.',
  'Love grows stronger every time understanding is chosen over pride.',
  'Sometimes forever begins with one ordinary hello.',
  'A heart that feels seen will always find the courage to bloom.',
  'The right person won\'t rescue you. They\'ll remind you how strong you\'ve always been.',
  'Love leaves its deepest mark through consistency, not intensity.',
  'Some connections feel familiar because they bring out the version of you you\'ve been searching for.',
  'The safest love is the one where silence never feels lonely.',
  'Choose the people who make peace feel natural.',
  'The greatest love stories aren\'t the loudest. They\'re the most genuine.',
  'Home isn\'t always a place. Sometimes it\'s simply a person who makes your heart exhale.',
  'The right love will never make you compete for a place in someone\'s heart.',
  'Some hearts recognize each other long before they understand why.',
  'Love becomes unforgettable when someone remembers the little things you never thought mattered.',
  'The most meaningful "I love you" is often spoken through everyday actions.',
  'A relationship grows stronger every time two people choose understanding over being right.',
  'You deserve a love that feels like coming home after a long journey.',
  'The right person won\'t complete your story. They\'ll help you write better chapters.',
  'Some people enter your life softly, then become impossible to imagine living without.',
  'Love isn\'t measured by perfect days, but by how gently you carry each other through difficult ones.',
  'When someone truly loves you, your heart no longer has to guess.',
  'The best relationships are built by two people who never stop learning each other.',
  'The kindest love gives you room to grow without fearing you\'ll grow apart.',
  'Real love listens to what words cannot say.',
  'Every meaningful relationship begins with someone choosing curiosity over judgment.',
  'Love becomes stronger every time forgiveness is chosen before pride.',
  'The people who matter most will never make you feel like you\'re too much.',
  'A heart that feels safe has the courage to dream bigger.',
  'The greatest gift you can offer someone is making them feel completely seen.',
  'The right love doesn\'t steal your freedom. It gives you the confidence to fly farther.',
  'Some people become your favorite place without ever becoming a destination.',
  'The right love won\'t ask you to become less. It will inspire you to become more.',
  'Some people enter your life like sunrise—quietly, gently, and changing everything.',
  'Love is knowing someone has seen your storms and still chooses to stay.',
  'The most beautiful relationships are built by two people who never stop choosing each other.',
  'A heart that feels accepted has nothing left to prove.',
  'Real love doesn\'t ask you to hide the parts of yourself you\'re still healing.',
  'The right person will never make peace feel temporary.',
  'Some souls don\'t cross your path by accident. They arrive exactly when your heart is ready.',
  'Love becomes extraordinary when being understood matters more than being impressive.',
  'The strongest bond is created through thousands of small moments no one else ever sees.',
  'A gentle heart will always recognize another gentle heart.',
  'Being loved shouldn\'t feel confusing. It should feel like breathing a little easier.',
  'The people who truly belong in your life will never make you question your place in it.',
  'Some conversations quietly become memories you\'ll carry forever.',
  'The best love stories aren\'t written by fate alone. They\'re written by two people who keep choosing each other.',
  'When love is real, silence becomes comfortable instead of heavy.',
  'The greatest romance begins the day two people feel completely safe being themselves.',
  'Love isn\'t about finding someone who changes your life overnight. It\'s about finding someone who makes every ordinary day feel meaningful.',
  'One genuine heart can heal places that years of loneliness could never reach.',
  'The deepest kind of love is finding someone who feels like peace in a world that rarely slows down.',
] as const

export type LoveLight = (typeof LOVE_LIGHTS)[number]
