/**
 * VORA Light quotes — Health
 * Original brand voice. Do not dilute with cliché motivational copy.
 */
export const HEALTH_LIGHTS = [
  'Your body has never asked for perfection. Only a little kindness.',
  'Drink water. Your body sends thank-you notes in energy.',
  'Your mind deserves the same care you give your favorite people.',
  'Rest isn\'t falling behind. It\'s how you stay in the story.',
  'Your body has carried every version of you. Treat it like an old friend.',
  'Sleep is one of the few things money can\'t replace.',
  'Take a deep breath. Your heart has been working overtime.',
  'Health isn\'t about looking stronger. It\'s about feeling more alive.',
  'You don\'t have to earn rest. You only have to need it.',
  'Eat food that loves you back.',
  'Your body hears every word you say about it. Choose kinder ones.',
  'The healthiest relationship you\'ll ever have is the one with yourself.',
  'Stress knocks on every door. You don\'t have to invite it in.',
  'Healing isn\'t a race. Your body has never been competing.',
  'Energy is a form of wealth. Spend it wisely.',
  'A peaceful mind makes every place feel a little more like home.',
  'Take care of your body. It\'s been cheering for you from the very beginning.',
  'Being healthy isn\'t about having more years. It\'s about having more life in your years.',
  'Give yourself the kind of care you never hesitate to give others.',
  'Your future doesn\'t need a perfect you. It needs a healthy one.',
  'Stand up for a minute. Your body misses moving.',
  'Your shoulders have been carrying enough. Let them rest.',
  'You don\'t have to solve everything today. Your nervous system will appreciate that.',
  'Take the long way home once in a while. Your mind enjoys new scenery.',
  'A full schedule isn\'t always a full life.',
  'The best investment you\'ll ever make is in the person living inside your body.',
  'Your heartbeat has never taken a day off. Show it a little gratitude.',
  'Pause for a breath. Your thoughts can wait their turn.',
  'You deserve meals that nourish you and moments that nourish your soul.',
  'Being busy isn\'t the same as being well.',
  'Drink water before your next excuse.',
  'Your body isn\'t asking for punishment. It\'s asking for partnership.',
  'Go outside. Fresh air has excellent conversation skills.',
  'Your health grows through small choices made with love instead of guilt.',
  'Stop apologizing for needing rest.',
  'Take care of yourself with the same patience you\'d offer someone you love.',
  'The goal isn\'t to do more. It\'s to feel better.',
  'A calm mind makes wiser decisions.',
  'You don\'t have to be perfect to take good care of yourself.',
  'Health isn\'t another task on your list. It\'s the reason you can enjoy everything else.',
  'Blink. Your eyes have been working harder than you realize.',
  'Your body isn\'t a machine. Stop expecting factory settings.',
  'Take a walk. Your thoughts enjoy stretching too.',
  'You don\'t have to carry stress like it\'s part of your outfit.',
  'Your body is listening. Speak to it with respect.',
  'A short break can rescue a very long day.',
  'Move because you love your body. Not because you\'re trying to fix it.',
  'The mirror tells one story. Your energy tells the real one.',
  'Your muscles forgive slowly. Be nicer to them today.',
  'A peaceful meal is healthy too.',
  'Don\'t forget to unclench your jaw. It has done nothing wrong.',
  'A tired mind tells louder lies. Get some rest before believing them.',
  'Your body isn\'t falling behind. It\'s asking to be heard.',
  'Drink water. Your future self has excellent taste.',
  'Health isn\'t measured only in years. It\'s measured in moments you truly enjoy.',
  'Take care of yourself before life reminds you to.',
  'You don\'t have to rush healing. Your body already knows the way.',
  'Put your phone down. Your neck has a few opinions.',
  'The strongest habit is choosing yourself again tomorrow.',
  'You only get one place to live forever. Your body happens to be it.',
  'Roll your shoulders. They\'ve been carrying more than your backpack.',
  'Step outside. The sky has been saving a seat for you.',
  'Your body isn\'t interrupting your plans. It\'s joining the conversation.',
  'A glass of water is a surprisingly kind way to say, "I\'ve got you."',
  'The strongest routine is the one you actually enjoy.',
  'Stop waiting until you\'re exhausted to deserve a break.',
  'Your mind blooms when your body feels cared for.',
  'Good health isn\'t built through guilt. It\'s built through respect.',
  'Take the stairs if you can. Take the elevator if you need to. Both are okay.',
  'Your body remembers how you treat it on ordinary days.',
  'You don\'t have to feel your best to do one good thing for yourself.',
  'Stretch a little. Your future self will notice.',
  'Choose progress over pressure. Your body prefers that too.',
  'The healthiest habit is showing up for yourself with compassion.',
  'Your body has been reading your choices. Give it a chapter worth smiling about.',
  'Eat something that gives you energy, not just something that fills the time.',
  'The goal isn\'t to fight your body. The goal is to become its favorite teammate.',
  'You can\'t pour from an empty cup. Refill without feeling guilty.',
  'Feeling better is worth celebrating, even if nobody else notices.',
  'Take care of yourself today. Tomorrow is built from moments like this.',
  'Your calendar can wait. Your body shouldn\'t have to.',
  'Take a stretch break. Your spine has been remarkably patient.',
  'You don\'t have to change everything. One healthy choice is a beautiful beginning.',
  'The healthiest version of you still laughs, rests, and enjoys dessert.',
  'Choose habits that make your life feel bigger, not just longer.',
  'You can\'t rush well-being. It grows through the choices you repeat.',
  'A calm breath can change the next hour of your day.',
  'Your body doesn\'t need constant criticism. It needs consistent care.',
  'Eat slowly. Good moments deserve more than one bite.',
  'Put your feet on the ground. It\'s a gentle reminder that you\'re here.',
  'Health isn\'t about becoming someone else. It\'s about taking better care of the person you already are.',
  'Smile at yourself once in a while. Your brain is paying attention.',
  'Move in ways that make you happy. That\'s a workout worth repeating.',
  'You don\'t have to do everything right. You only have to keep choosing yourself.',
  'The healthiest routine is the one that still leaves room for joy.',
  'Your body notices every act of kindness, even the small ones.',
  'Take another breath. You\'ve made it through every difficult day so far.',
  'A healthier life is built through little promises you keep to yourself.',
  'The person who needs your care the most has been with you all along.',
  'Take good care of yourself. The world is brighter when you\'re in it.',
] as const

export type HealthLight = (typeof HEALTH_LIGHTS)[number]
