/**
 * VORA Light quotes — Dream
 * Original brand voice. Do not dilute with cliché motivational copy.
 */
export const DREAM_LIGHTS = [
  'The dream that stays with you is usually the one meant for you.',
  'Some dreams wait patiently because they know exactly who you\'re becoming.',
  'Never let today\'s limits decide tomorrow\'s possibilities.',
  'The life you imagine begins the moment you stop doubting it.',
  'Every remarkable journey starts as a quiet thought no one else can see.',
  'Dreams don\'t ask for perfection. They ask for persistence.',
  'One day, you\'ll realize your dream was quietly shaping you all along.',
  'The future belongs to those who protect their dreams from their fears.',
  'Some dreams arrive before you\'re ready so you\'ll have a reason to grow.',
  'Keep following what makes your heart feel awake.',
  'A dream becomes a destination the moment you decide it deserves your effort.',
  'Every great story begins with someone believing in a future no one else could imagine.',
  'Don\'t abandon your dream just because the road became unfamiliar.',
  'The stars were never meant to be reached in a single night.',
  'Sometimes the dream changes you before you ever reach it.',
  'Your imagination has already visited places your courage is still learning to find.',
  'The dream that\'s meant for you will keep calling until you answer.',
  'Every sunrise is another invitation to continue the story you\'ve only just begun.',
  'The most beautiful dreams are often the ones that ask you to become someone new.',
  'One quiet decision today can become tomorrow\'s impossible achievement.',
  'Some dreams whisper because they\'re waiting for you to listen more closely.',
  'Your dream chose you for a reason. Don\'t leave it unanswered.',
  'The future you imagine is already taking shape in today\'s smallest decisions.',
  'Dreams become reality one courageous choice at a time.',
  'Never confuse a slow journey with a forgotten dream.',
  'Every dream asks one question: "Will you keep going?"',
  'The road to your dream doesn\'t need to be clear. It only needs your next step.',
  'The most extraordinary futures begin with ordinary acts of courage.',
  'One day, your dream will thank you for not giving up on it.',
  'Sometimes the biggest leap begins with believing one quiet possibility.',
  'Your dream is growing every time you choose hope over hesitation.',
  'There is a version of your life that\'s waiting for your courage to catch up.',
  'Dreams don\'t disappear. They patiently wait for your return.',
  'The path may change, but the dream can still remain true.',
  'Every impossible vision begins as something only one person can see.',
  'The dream worth chasing is the one that keeps finding its way back to your heart.',
  'Some destinations are beautiful because of everything they ask you to become.',
  'Every step toward your dream is also a step toward yourself.',
  'The future isn\'t found. It\'s imagined first.',
  'Protect your dream until it\'s strong enough to speak for itself.',
  'The dream that refuses to leave your heart may be the one you\'re meant to live.',
  'Some dreams grow quietly because they\'re preparing something extraordinary.',
  'Your future begins wherever your courage finally says yes.',
  'Dreams ask for patience long before they offer proof.',
  'Every meaningful journey begins with believing before seeing.',
  'The life you\'re hoping for is slowly becoming possible through today\'s choices.',
  'Some dreams take time because they\'re building someone strong enough to carry them.',
  'A dream becomes real the moment it becomes part of your daily life.',
  'Keep walking toward what makes your soul feel alive.',
  'Every chapter you write today becomes part of tomorrow\'s impossible story.',
  'Your imagination is showing you places your future is still traveling toward.',
  'Dreams don\'t need perfect timing. They need faithful hearts.',
  'One decision made with hope can outgrow years of fear.',
  'Sometimes your dream is closer than your doubts allow you to believe.',
  'The future belongs to those who keep believing after certainty disappears.',
  'A dream isn\'t measured by how quickly it happens, but by how deeply it changes you.',
  'Every sunrise is another page your dream is waiting for you to write.',
  'The road may be longer than expected, but so is the view waiting at the end.',
  'One quiet promise to your future self can become the beginning of everything.',
  'The greatest dreams don\'t simply change your destination. They transform the traveler.',
  'The dreams that stay with you are often the ones that know your name.',
  'One quiet step today is still carrying you toward tomorrow.',
  'Your dream isn\'t waiting for perfection. It\'s waiting for your courage.',
  'Every sunrise is another chance to choose the life you\'ve imagined.',
  'Some dreams bloom slowly because they\'re growing deep roots first.',
  'The future becomes real the moment you decide it deserves your effort.',
  'Every dream asks you to become someone stronger before it becomes yours.',
  'The life you long for begins with the choices you make when no one is watching.',
  'Dreams become brighter every time fear loses its vote.',
  'Trust the journey that\'s teaching you who you\'re meant to become.',
  'Some destinations are beautiful because they couldn\'t be reached too soon.',
  'Your dream has been patiently waiting for the day you believe it belongs to you.',
  'The smallest act of courage can awaken the biggest dream.',
  'Every impossible future begins as a quiet possibility.',
  'The dream that scares you most may also be the one that frees you most.',
  'You are allowed to outgrow the life you once thought was enough.',
  'One faithful step is always stronger than a hundred perfect plans.',
  'Keep protecting your dream until it no longer needs protection.',
  'Your tomorrow is listening to every choice you make today.',
  'One day you\'ll smile, realizing your dream had been finding its way to you all along.',
  'Some dreams don\'t chase you. They patiently wait for you to become brave enough.',
  'The future you\'ve imagined is quietly growing through every choice you make today.',
  'Your dream isn\'t asking whether you\'re ready. It\'s asking whether you\'re willing.',
  'The most extraordinary lives begin with one ordinary moment of courage.',
  'Some dreams feel impossible because they\'re introducing you to a version of yourself you\'ve never met.',
  'Never underestimate the power of a dream that refuses to leave your heart.',
  'Every dream carries two gifts: the destination and the person you\'ll become along the way.',
  'Your heart remembers the dreams your fears try to make you forget.',
  'One bold decision can give your future an entirely new direction.',
  'The dream that\'s meant for you will keep knocking until you answer.',
  'Sometimes the longest road leads to the life that fits you best.',
  'The stars don\'t rush to shine. Neither should your dreams.',
  'Every step forward is another promise kept to the future you\'ve imagined.',
  'Dreams don\'t become impossible because they\'re too big. They become impossible when they\'re abandoned.',
  'Keep choosing the life that makes your soul feel more alive.',
  'The future belongs to those who stay loyal to the dreams that first inspired them.',
  'One day you\'ll realize your dream was quietly guiding your choices long before you noticed.',
  'Your greatest adventure begins the moment you stop asking for permission.',
  'The dream worth chasing is the one that keeps calling you home to yourself.',
  'Some dreams change the world. The best ones change you first.',
] as const

export type DreamLight = (typeof DREAM_LIGHTS)[number]
